Feature/aos 5328 auroraconfig files
Skatteetaten/gobo pull request #210
Opened 2021-01-29 08:35 UTC by RuneOfferdal

Sørger for at man kan nå filenames med affiliations som rot-query.

2021-01-29 10:28 UTC, jarlehansen requested changes

2021-01-29 10:28 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/graphql/auroraconfig/AuroraConfigDataLoader.kt
> +    val refInput: String?,
hva med å sette denne til 
```
val refInput: String = "master"
```

Så slipper du ?: koden under

2021-01-29 10:28 UTC, jarlehansen commented on src/test/kotlin/no/skatteetaten/aurora/gobo/graphql/auroraconfig/AuroraConfigFilesNamesQueryTest.kt
> +            .graphqlDataWithPrefix("affiliations.items") {
kan være `affiliations.items[0]`så slipper du [0] under

2021-01-29 10:42 UTC, RuneOfferdal commented on src/main/kotlin/no/skatteetaten/aurora/gobo/graphql/auroraconfig/AuroraConfigDataLoader.kt
> +    val refInput: String?,
Fikser.

2021-01-29 10:43 UTC, RuneOfferdal commented on src/test/kotlin/no/skatteetaten/aurora/gobo/graphql/auroraconfig/AuroraConfigFilesNamesQueryTest.kt
> +            .graphqlDataWithPrefix("affiliations.items") {
Jepp. Fikser.

2021-01-29 11:30 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/graphql/auroraconfig/AuroraConfigDataLoader.kt
> +    val refInput: String?,
ja, ser den. kanskje best å beholde som den er

2021-01-29 11:39 UTC, jarlehansen approved these changes

2021-01-29 12:14 UTC, bugge-jorgen approved these changes

2021-02-01 07:44 UTC, RuneOfferdal commented on src/test/kotlin/no/skatteetaten/aurora/gobo/graphql/auroraconfig/AuroraConfigFilesNamesQueryTest.kt
> +            .graphqlDataWithPrefix("affiliations.items") {
Nytt forsøk og det fungerte. Fikset.

2021-02-01 08:03 UTC, merged