AOS-5206: Implemented mutation to delete vault.
Skatteetaten/gobo pull request #213
Opened 2021-02-02 10:13 UTC by bugge-jorgen

2021-02-02 11:20 UTC, jarlehansen requested changes

2021-02-02 11:20 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/integration/boober/VaultService.kt
> +        input: DeleteVaultInput
Dette er bagateller, men jeg foretrekker at service-klassene ikke kjenner til graphql typene. Tror jeg ville sendt inn affiliationName og vaultName som input parametere her

2021-02-02 11:20 UTC, jarlehansen commented on src/test/kotlin/no/skatteetaten/aurora/gobo/graphql/vault/VaultMutationTest.kt
> +            .graphqlData("deleteVault").isEqualTo("true")
Delete vault bør ikke returnere bare "true". Hva med å returnere DeleteVaultResponse? Det er viktig at vi returnerer typer fra mutations, og ikke bare primitiver. Dette gjør det mye enklere å utvide/endre senere

2021-02-02 12:11 UTC, bugge-jorgen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/integration/boober/VaultService.kt
> +        input: DeleteVaultInput
Fikset

2021-02-02 12:11 UTC, bugge-jorgen commented on src/test/kotlin/no/skatteetaten/aurora/gobo/graphql/vault/VaultMutationTest.kt
> +            .graphqlData("deleteVault").isEqualTo("true")
Fikset

2021-02-02 12:18 UTC, jarlehansen approved these changes

2021-02-02 22:43 UTC, oyvinder commented on src/main/kotlin/no/skatteetaten/aurora/gobo/graphql/vault/VaultMutation.kt
> +        vaultService.deleteVault(dfe.token(), input.affiliationName, input.vaultName)
Bør vi ha validering av input her? Eller overlate det til boober?

2021-02-03 11:05 UTC, oyvinder commented on src/main/kotlin/no/skatteetaten/aurora/gobo/graphql/vault/VaultMutation.kt
> +        vaultService.deleteVault(dfe.token(), input.affiliationName, input.vaultName)
Vi kan følge opp dette i en egen sak.

2021-02-03 11:06 UTC, oyvinder approved these changes

2021-02-04 07:29 UTC, bugge-jorgen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/graphql/vault/VaultMutation.kt
> +        vaultService.deleteVault(dfe.token(), input.affiliationName, input.vaultName)
Inputvalidering opprettes som en egen JIRA-sak, har sendt mail til Øyvind om dette 2021.02.04.

2021-02-04 07:29 UTC, merged