Feature/aos 5450 vault input validation
Skatteetaten/gobo pull request #222
Opened 2021-02-17 18:50 UTC by bugge-jorgen

2021-02-18 12:01 UTC, jarlehansen requested changes

2021-02-18 12:01 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/integration/boober/VaultService.kt
> +        val vault = getVault(ctx)
kunne dette vært flyttet til en felles funksjon, ser at samme går igjen flere ganger

2021-02-18 12:01 UTC, jarlehansen commented on src/main/resources/application.yaml
> +        herkimer: ${integrations.herkimer.url}
skal ikke med, fjernes

2021-02-18 12:01 UTC, jarlehansen commented on src/main/resources/application-local.yaml
> +        url: https://herkimer-aurora.utv.paas.skead.no
skal ikke med, fjernes

2021-02-18 12:01 UTC, jarlehansen commented on src/main/resources/application.yaml
> +        url: http://herkimer
skal ikke med, fjernes

2021-02-18 13:11 UTC, bugge-jorgen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/integration/boober/VaultService.kt
> +        val vault = getVault(ctx)
Litt usikker på hva du mener her Jarle. getVault() er jo skilt ut som en egen one-liner-funksjon. Det er videre slik at getVault() skal kalles i enkelte tilfeller , emn ikke alle.

2021-02-18 13:11 UTC, bugge-jorgen commented on src/main/resources/application.yaml
> +        herkimer: ${integrations.herkimer.url}
OK

2021-02-18 13:12 UTC, bugge-jorgen commented on src/main/resources/application-local.yaml
> +        url: https://herkimer-aurora.utv.paas.skead.no
OK

2021-02-18 13:12 UTC, bugge-jorgen commented on src/main/resources/application.yaml
> +        url: http://herkimer
OK

2021-02-18 15:57 UTC, bugge-jorgen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/integration/boober/VaultService.kt
> +        val vault = getVault(ctx)
Det er forskjellige meldinger og forskjllige tester (positiv og negativ) test så vi ble enige om at det ikke var noe å spare på å trekke dette ut i egen funksjon.

2021-02-19 09:05 UTC, oyvinder approved these changes

2021-02-19 09:05 UTC, oyvinder commented on src/main/kotlin/no/skatteetaten/aurora/gobo/integration/boober/VaultService.kt
> +        val vault = getVault(ctx)
Her forutsetter vi at getVaut() returnerer feil, og ikke vault med redusert innhold, dersom man ikke har tilgang.
Men det blir kanskje "bloated" å sjekke på hasAccess.

2021-02-19 10:56 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/integration/boober/VaultService.kt
> +        val vault = getVault(ctx)
godt poeng, vi bør sjekke hasAccess også

2021-02-19 13:34 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/integration/boober/VaultService.kt
> +        val vault = getVault(ctx)
et litt annet forslag, hva om vi på `getVault` sjekker om hasAccess er false også kaster exception? Jeg syns dette med `hasAccess` er et litt svakt designvalg fra boober, og vi trenger vel ikke å fortsette med det i boober? Hva tenker du @oyvinder

2021-02-19 13:35 UTC, jarlehansen approved these changes

2021-02-19 14:13 UTC, merged