graphql-kotlin 4.0
Skatteetaten/gobo pull request #233
Opened 2021-04-23 04:42 UTC by jarlehansen

2021-04-28 10:41 UTC, mikand13 requested changes

2021-05-03 06:52 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/graphql/webseal/WebsealState.kt
> +    fun junctions(propertyNames: List<String>? = null) = junctions.map { junction ->
dessverre så må den input parameteren være nullable, slik at den blir optional i graphql. Da tjener vi ikke noe særlig på å endre alle disse til emptyList() eller noe lignende, for vi må uansett null-sjekke.

2021-05-03 12:07 UTC, mikand13 approved these changes
Bare få lagd en sak på å migrere fullstendig vekk fra det gamle så ser det greit ut for meg

2021-05-04 11:04 UTC, oyvinder approved these changes

2021-05-05 05:15 UTC, jarlehansen commented
Har laget AOS-5682 for å fikse de gamle dataloaderne

2021-05-05 05:26 UTC, merged