updated to new GraphqlContext, added logging of graphql operation start and finish
Skatteetaten/gobo pull request #261
Opened 2021-11-25 12:09 UTC by jarlehansen

…rt and finish

2021-11-29 12:56 UTC, mikand13 requested changes

2021-11-29 12:56 UTC, mikand13 commented on src/test/kotlin/no/skatteetaten/aurora/gobo/graphql/certificate/CertificateQueryTest.kt
>              .graphqlData("certificates.totalCount").isEqualTo(2)
Hvilken relevans har disse kommentarene?

2021-11-30 08:51 UTC, jarlehansen commented on build.gradle.kts
> +    id("org.flywaydb.flyway") version "8.0.5"
prøver å fjerne flyway plugin, tror egentlig ikke den trengs

2021-11-30 08:54 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/graphql/GoboDataLoader.kt
> +                    getByKeys(keys, (env.keyContexts.entries.first().value as GoboGraphQLContext).context)
fikser

2021-11-30 08:56 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/graphql/GoboGraphQLContextFactory.kt
> +        val reactorContext =
fikser

2021-11-30 08:59 UTC, jarlehansen commented on src/test/kotlin/no/skatteetaten/aurora/gobo/graphql/certificate/CertificateQueryTest.kt
>              .graphqlData("certificates.totalCount").isEqualTo(2)
debugging kode som bare er glemt igjen :) skal fikse.

2021-12-02 13:55 UTC, bugge-jorgen approved these changes
Massive endringer! Viser også til gjennomgang på WS på onsdag. Jeg har ikke noen kommentarer, jeg mener det ser veldig greit ut.

2021-12-03 08:44 UTC, mikand13 approved these changes

2021-12-09 10:42 UTC, merged