AOS-6337: Henter versjoner fra nytt endepunkt i Cantus
Skatteetaten/gobo pull request #282
Opened 2022-03-23 09:47 UTC by TomasEng

2022-04-07 11:22 UTC, jarlehansen requested changes

2022-04-07 11:22 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/graphql/imagerepository/VersionDataLoader.kt
> +        if (keys.isEmpty()) return emptyMap()
Trenger du denne?

2022-04-07 11:22 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/graphql/imagerepository/VersionsDataLoader.kt
> +                when {
Bare 2 brancher her, kan kanskje lige gjerne ha en if/else statement?

2022-04-07 11:25 UTC, TomasEng commented on src/main/kotlin/no/skatteetaten/aurora/gobo/graphql/imagerepository/VersionDataLoader.kt
> +        if (keys.isEmpty()) return emptyMap()
Nei, den er vel ikke nødvendig nei

2022-04-08 08:58 UTC, jarlehansen approved these changes

2022-04-19 11:34 UTC, stromland approved these changes

2022-04-22 12:50 UTC, merged