Bugfix/aos 5593 applicationfiles
Skatteetaten/gobo pull request #283
Opened 2022-03-31 11:11 UTC by martinrodland

2022-04-01 09:16 UTC, jarlehansen requested changes

2022-04-01 09:16 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/graphql/auroraconfig/ApplicationFilesResourceDataLoader.kt
> +                ApplicationFilesResource(
service kall + filter inne i oppbyggingen her syns jeg er vanskelig å følge med på.
Kanskje sette på en egen linje over instansieringen av `ApplicationFilesResource`?

2022-04-01 11:26 UTC, martinrodland commented on src/main/kotlin/no/skatteetaten/aurora/gobo/graphql/auroraconfig/ApplicationFilesResourceDataLoader.kt
> +                ApplicationFilesResource(
enig, skal endre på det :)

2022-04-01 11:56 UTC, jarlehansen approved these changes

2022-04-04 11:43 UTC, kris456 approved these changes

2022-04-04 12:23 UTC, furode approved these changes

2022-04-06 17:42 UTC, stromland approved these changes

2022-04-07 10:27 UTC, merged