Feature/aos 6770 gjenskape504
Skatteetaten/gobo pull request #314
Opened 2022-07-12 10:22 UTC by bugge-jorgen

2022-07-25 14:27 UTC, jarlehansen requested changes

2022-07-25 14:27 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/graphql/errorhandling/GoboDataFetcherExceptionHandler.kt
>  class GoboDataFetcherExceptionHandler(@Value("\${integrations.boober.url}") private val booberUrl: String) :
Denne fiksen bør inn i master, skal vi dra den ut i en egen PR?
Må også fikse testen vi Disablet

2022-07-25 14:27 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/graphql/GoboDataLoader.kt
> +                }.asCompletableFuture().orTimeout(3, TimeUnit.MINUTES)
Dette må også merges inn i master

2022-07-25 14:28 UTC, jarlehansen commented
De gatling testene, bør vi ta oss tiden til å skrive de i Kotlin?
Usikker på hvor mye mer jobb det er, men vi kunne fått de mye bedre og hatt mye mer kontroll hvis det er Kotlin kode.

2022-08-23 07:03 UTC, bugge-jorgen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/graphql/errorhandling/GoboDataFetcherExceptionHandler.kt
>  class GoboDataFetcherExceptionHandler(@Value("\${integrations.boober.url}") private val booberUrl: String) :
Kan vi ta en prat om denne?

2022-08-23 07:19 UTC, bugge-jorgen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/graphql/GoboDataLoader.kt
> +                }.asCompletableFuture().orTimeout(3, TimeUnit.MINUTES)
Fiks: Ikke konfigurerbar, settes til 5 min

2022-09-15 13:13 UTC, oyvinder commented on src/gatling/resources/mokey_add_latency_toxic_mutation.json
> +          "stream": "upstream",
Er det mer logisk riktig å bruke "downstream" her? 
Det er default, og passer bedre dersom vi skal simulere forsinkelser i svaret fra baksystemet.

2022-10-07 08:55 UTC, bugge-jorgen commented on src/main/kotlin/no/skatteetaten/aurora/gobo/graphql/errorhandling/GoboDataFetcherExceptionHandler.kt
> +            |  path="$path" ${dataFetchingEnvironment.query} timeUsed="$timeUsed"
JB: Sjekk om denne er i master, hvis ikke merge den inn.

2022-10-11 09:39 UTC, closed without merging